const String localAdStr="ewogICJydXNoZ2tlbCI6IDEwMCwKICAianVlaG5icmEiOiAxMDAsCiAgInNxZnRtX2ludF9vbmUiOiBbCiAgICB7CiAgICAgICJwcXVybmtnbyI6ICI0ZjViYTU2Zjc1ZDYwNDE2IiwKICAgICAgInZqc2lsZm9zIjogIm1heCIsCiAgICAgICJ0dXNrZW50bCI6ICJpbnRlcnN0aXRpYWwiLAogICAgICAibWVyeXNsYWYiOiAzMDAwLAogICAgICAib2prZWxnZGciOiAzCiAgICAgfQogIF0sCiAgInNxZnRtX3J2X29uZSI6IFsKICAgICB7CiAgICAgICJwcXVybmtnbyI6ICJiNjEyNjY2ZTI2N2VkZDdmIiwKICAgICAgInZqc2lsZm9zIjogIm1heCIsCiAgICAgICJ0dXNrZW50bCI6ICJyZXdhcmQiLAogICAgICAibWVyeXNsYWYiOiAzMDAwLAogICAgICAib2prZWxnZGciOiAzCiAgICB9CiAgXQp9";
const String maxKey="TVdKemhuRVB0S3F4TEtSTEFsVnJUeVFmTzJWeFdaV3RWeF9TelRXQ19NZ29aTDdrVEtOdDl0M01fT2dJWjI0bkJYUlh4VmQ5b2dRRXA3NjE2VFdmM0M=";
const String privacy="https://scratchfuntimepro.com/privacy/";
const String email="rackefellef@nahum-travels.com";
const String tbaUrl="https://butchery.scratchfuntimepro.com/hydrogen/gibbet";
const String cloakUrl="https://colonist.scratchfuntimepro.com/please/pixy/edwin";